Models/Emlak.cs
namespace finalcal.Models
{
    public class Emlak
    {
        public int id { get; set; }
        public string konum { get; set; }
        public int fiyat { get; set; }
    }
}

Models/EmlakDbContext.cs
using finalcal.Models;
using Microsoft.EntityFrameworkCore;


namespace finalcal
{
    public class EmlakDbContext : DbContext
    {
        public DbSet<Emlak> Emlaklar { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=EmlakDbMvcFinalcal;Integrated Security=true");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Emlak>().ToTable("tblemlaklar");

            modelBuilder.Entity<Emlak>().Property(o => o.konum).HasColumnType("varchar").HasMaxLength(25).IsRequired();

            modelBuilder.Entity<Emlak>().Property(o => o.fiyat).HasColumnType("varchar").HasMaxLength(30).IsRequired();

            
        }
    }
}

Models/ErrorViewModel.cs
namespace finalcal.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EmlakController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using finalcal.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace finalcal.Controllers
{
    public class EmlakController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult EmlakEkle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult EmlakEkle(Emlak eml)
        {
            if(eml != null)
            {
                using (var ctx = new EmlakDbContext())
                {
                    ctx.Emlaklar.Add(eml);
                    ctx.SaveChanges();
                }
            }
            return View();
        }


       
        public IActionResult EmlakListe()
        {
            List<Emlak> lst = null;
            using (var ctx = new EmlakDbContext())
            {
                lst = ctx.Emlaklar.ToList();
            }

                return View(lst);
        }

        public IActionResult EmlakSil(int? id)
        {
            using (var ctx = new EmlakDbContext())
            {
                var eml = ctx.Emlaklar.Find(id);
                ctx.Remove(eml);
                ctx.SaveChanges();
            }


            return RedirectToAction("emlakliste");
        }

        public IActionResult EmlakDuzenle(int? id)
        {
            Emlak eml = null;
            using (var ctx = new EmlakDbContext())
            {
                eml = ctx.Emlaklar.Find(id);
            }

            return View(eml);
        }

        [HttpPost]
        public IActionResult EmlakDuzenle(Emlak eml)
        {
            using(var ctx = new EmlakDbContext())
            {
                ctx.Entry(eml).State = EntityState.Modified;
                ctx.SaveChanges();
            }

            return RedirectToAction("EmlakListe");
        }


    }
}

Controllers/HomeController.cs
using finalcal.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace finalcal.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Emlak/EmlakDuzenle.cshtml
@model finalcal.Models.Emlak
@{
    ViewData["Title"] = "EmlakDuzenle";
}

<h1>EmlakDuzenle</h1>

<div>
    <h4>Ogrenci</h4>
    <hr />
    <form asp-action="EmlakDuzenle" asp-controller="Emlak" method="post">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.konum)
            </dt>
            <dd class="col-sm-10">
                @Html.TextBoxFor(model => model.konum)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.fiyat)
            </dt>
            <dd class="col-sm-10">
                @Html.TextBoxFor(model => model.fiyat)
            </dd>
        </dl>
        <input type="submit" value="Kaydet" class="btn btn-outline-success" onclick="return confirm('Emlak düzenlenecek')" />
        @Html.HiddenFor(o=>o.id)
    </form>
</div>
<div>    |
    <a asp-action="EmlakListe" asp-controller="Emlak">Back to List</a>
</div>

Views/Emlak/EmlakEkle.cshtml
@model Emlak
@{
    ViewData["Title"] = "Emlakekle";
}

<h1>Emlakekle</h1>

<form asp-controller = "Emlak" asp-action = "EmlakEkle" method = "post">

    <label>konum</label>
    <input type = "text" asp-for = "konum" />
    <label>fiyat</label>
    <input type = "text" asp-for = "fiyat" />


    <input type = "submit" value = "kaydet" />


</form>

Views/Emlak/EmlakListe.cshtml
@model IEnumerable<Emlak>
@{
    ViewData["Title"] = "EmlakListe";
}

<h1>EmlakListe</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>İD</th>
            <th>Fiyat</th>
            <th>Konum</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.id</td>
                <td>@item.fiyat</td>
                <td>@item.konum</td>
                <td><a href="/Emlak/EmlakDuzenle/@item.id" class="btn btn-sm btn-primary text-white">Düzenle</a>  <a href="/Emlak/EmlakSil/@item.id" class="btn btn-sm btn-danger text-white" onclick="return confirm('Emin misiniz?')">Sil</a></td>
            </tr>
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - finalcal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/finalcal.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">finalcal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - finalcal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>